"""phase 2 options research cluster

Revision ID: 5beabd636c8f
Revises: 94d5578ff40d
Create Date: 2026-08-08 07:00:07.863054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5beabd636c8f'
down_revision: Union[str, Sequence[str], None] = '94d5578ff40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('flights', 'hotels', 'activities', 'full', name='research_run_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='research_run_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_api_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_run_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('serpapi_flights_search', 'serpapi_flights_booking', 'serpapi_hotels_search', 'serpapi_hotels_property', 'claude_web_search', 'claude_url_extract', name='raw_api_source'), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('option_type', sa.Enum('flight', 'hotel', 'activity', 'imported', name='option_type'), nullable=False),
    # Reuse Phase 1's budget_band enum. Must be postgresql.ENUM — sa.Enum ignores create_type
    # and would emit CREATE TYPE again.
    sa.Column(
        'tier',
        postgresql.ENUM('budget', 'comfort', 'premium', name='budget_band', create_type=False),
        nullable=False,
    ),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('base_price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_api_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_options',
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('estimated_price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_price_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.PrimaryKeyConstraint('option_card_id')
    )
    op.create_table('booking_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('deep_link_url', sa.String(), nullable=False),
    sa.Column('raw_response_id', sa.UUID(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.ForeignKeyConstraint(['raw_response_id'], ['raw_api_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_options',
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('booking_token', sa.String(), nullable=False),
    sa.Column('departure_airport', sa.String(), nullable=False),
    sa.Column('arrival_airport', sa.String(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('airlines', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('layovers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bags_included', sa.Boolean(), nullable=False),
    sa.Column('emissions_grams', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.PrimaryKeyConstraint('option_card_id')
    )
    op.create_table('hotel_options',
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('property_token', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('star_rating', sa.Numeric(precision=2, scale=1), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=False),
    sa.Column('free_cancellation', sa.Boolean(), nullable=False),
    sa.Column('eco_certified', sa.Boolean(), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.PrimaryKeyConstraint('option_card_id')
    )
    op.create_table('imported_options',
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('extracted_title', sa.String(), nullable=False),
    sa.Column('extracted_description', sa.Text(), nullable=True),
    sa.Column('category_hint', sa.String(), nullable=True),
    sa.Column('estimated_price_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_price_currency', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.PrimaryKeyConstraint('option_card_id')
    )
    op.create_table('locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leg_id', sa.UUID(), nullable=False),
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('locked_by_user_id', sa.UUID(), nullable=False),
    sa.Column('locked_price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('locked_currency', sa.String(length=3), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_booked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_locks_leg_id_active', 'locks', ['leg_id'], unique=True, postgresql_where=sa.text('unlocked_at IS NULL'))
    op.create_table('reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('option_card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reaction_type', sa.Enum('up', 'down', name='reaction_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_card_id'], ['option_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_card_id', 'user_id', name='uq_reactions_option_card_id_user_id')
    )
    op.create_table('citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_option_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_option_id'], ['activity_options.option_card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lock_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lock_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('locked', 'unlocked', 'relocked', 'marked_booked', 'unmarked_booked', name='lock_event_type'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lock_id'], ['locks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lock_events')
    op.drop_table('citations')
    op.drop_table('reactions')
    op.drop_index('uq_locks_leg_id_active', table_name='locks', postgresql_where=sa.text('unlocked_at IS NULL'))
    op.drop_table('locks')
    op.drop_table('imported_options')
    op.drop_table('hotel_options')
    op.drop_table('flight_options')
    op.drop_table('booking_sources')
    op.drop_table('activity_options')
    op.drop_table('option_cards')
    op.drop_table('raw_api_responses')
    op.drop_table('research_runs')
    # ### end Alembic commands ###
